server:
  port: 8081

spring:
  application:
    name: lab4-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lab4
    username: postgres_user
    password: postgres_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# Configurația de Resilience (mutată din properties)
resilience4j:
  circuitbreaker:
    instances:
      stableMatchService:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        slidingWindowSize: 10
  retry:
    instances:
      stableMatchService:
        maxAttempts: 3
        waitDuration: 2s
  timelimiter:
    instances:
      stableMatchService:
        timeoutDuration: 2s
